# https://taskfile.dev

version: "3"

output: "prefixed"

tasks:
  run:
    desc: run with downstream
    deps:
      [
        source,
        sfn,
        zipper,
        downstream-zipper,
        downstream-source,
        downstream-sfn,
      ]

  run-only-basic:
    desc: only run the very basic example
    deps: [zipper, source, sfn]
    cmds:
      - echo 'basic example run'

  # example cleanup
  clean:
    desc: example cleanup
    silent: true
    cmds:
      - echo 'example cleaning...'
      - rm -rf bin

  build:
    desc: build source, sfn and zipper
    deps: [source-build, sfn-build, zipper-build]
    cmds:
      - echo 'building done'

  source-build:
    desc: build basic source example
    cmds:
      - "go build -o ./bin/source{{exeExt}} source/main.go"

  zipper-build:
    desc: build basic zipper example
    cmds:
      - "go build -o ./bin/zipper{{exeExt}} zipper/main.go"
      - "cp zipper/workflow.yaml ./bin/."

  sfn-build:
    desc: build basic stream function
    cmds:
      - "go build -o ./bin/sfn{{exeExt}} sfn/main.go"

  source:
    desc: run basic source example
    deps: [source-build]
    cmds:
      - "./bin/source{{exeExt}}"
    env:
      YOMO_ENABLE_DEBUG: true
      YOMO_LOG_LEVEL: error

  sfn:
    desc: run basic stream function
    deps: [sfn-build]
    cmds:
      - "./bin/sfn{{exeExt}}"
    env:
      YOMO_ENABLE_DEBUG: true
      YOMO_LOG_LEVEL: error

  zipper:
    desc: run basic zipper service
    deps: [zipper-build]
    dir: bin
    cmds:
      # - "yomo serve -v -c zipper/workflow.yaml"
      - "cp ../zipper/workflow.yaml ."
      - "./zipper{{exeExt}}"
    env:
      YOMO_ENABLE_DEBUG: true
      YOMO_LOG_LEVEL: error
      YOMO_ADDR: "localhost:9000"
      YOMO_DOWNSTREAM_ADDR: "localhost:9001"

  downstream-zipper:
    desc: run basic zipper downstream service
    deps: [zipper-build]
    dir: "bin"
    cmds:
      - "./zipper{{exeExt}}"
    env:
      YOMO_ENABLE_DEBUG: true
      YOMO_LOG_LEVEL: info
      YOMO_ADDR: "localhost:9001"

  downstream-source:
    desc: run basic downstream source example
    deps: [source-build]
    dir: "bin"
    cmds:
      - "./source{{exeExt}}"
    env:
      YOMO_ENABLE_DEBUG: true
      YOMO_LOG_LEVEL: error
      YOMO_ADDR: "localhost:9001"

  downstream-sfn:
    desc: run basic downstream stream function
    deps: [sfn-build]
    dir: "bin"
    cmds:
      - "./sfn{{exeExt}}"
    env:
      YOMO_ENABLE_DEBUG: true
      YOMO_LOG_LEVEL: error
      YOMO_ADDR: "localhost:9001"
