# https://taskfile.dev

version: "3"

output: "prefixed"

includes:
  basic:
    taskfile: ./0-basic/Taskfile.yml
    dir: ./0-basic
  pipeline:
    taskfile: ./1-pipeline/Taskfile.yml
    dir: ./1-pipeline
  iopipe:
    taskfile: ./2-iopipe/Taskfile.yml
    dir: ./2-iopipe
  multi-sfn:
    taskfile: ./3-multi-sfn/Taskfile.yml
    dir: ./3-multi-sfn
  cascading-zipper:
    taskfile: ./4-cascading-zipper/Taskfile.yml
    dir: ./4-cascading-zipper
  backflow:
    taskfile: ./5-backflow/Taskfile.yml
    dir: ./5-backflow
  mesh:
    taskfile: ./6-mesh/Taskfile.yaml
    dir: ./6-mesh
  wasm:
    taskfile: ./7-wasm/Taskfile.yaml
    dir: ./7-wasm
  deno:
    taskfile: ./8-deno/Taskfile.yaml
    dir: ./8-deno
  cli:
    taskfile: ./9-cli/Taskfile.yaml
    dir: ./9-cli

tasks:
  example-basic:
    desc: YoMo basic usage
    silent: false
    cmds:
      - task: basic:run

  example-pipeline:
    desc: Unix pipeline to cloud
    silent: false
    cmds:
      - task: pipeline:run

  example-iopipe:
    desc: IO Pipe
    silent: false
    cmds:
      - task: iopipe:run

  example-multi-sfn:
    desc: Multiple stream functions
    silent: false
    cmds:
      - task: multi-sfn:run

  example-cascading-zipper:
    desc: Cascading zippers
    silent: false
    cmds:
      - task: cascading-zipper:run

  example-backflow:
    desc: Backflow usage
    silent: false
    cmds:
      - task: backflow:run

  example-mesh:
    desc: Edge mesh usage
    silent: false
    cmds:
      - task: mesh:run

  example-wasm:
    desc: WASM usage
    silent: false
    cmds:
      - task: wasm:run

  example-deno:
    desc: Deno usage
    silent: false
    cmds:
      - task: deno:run

  example-cli:
    desc: CLI usage
    silent: false
    cmds:
      - task: cli:run

  # example cleanup
  clean:
    desc: clean
    silent: true
    cmds:
      - echo 'example cleaning...'
      - task: basic:clean
      - task: pipeline:clean
      - task: iopipe:clean
      - task: multi-sfn:clean
      - task: cascading-zipper:clean
      - task: backflow:clean
      - task: mesh:clean
      - task: wasm:clean
      - task: deno:clean
      - task: cli:clean
