# https://taskfile.dev

version: "3"

output: "prefixed"

includes:
  basic:
    taskfile: ./0-basic/Taskfile.yml
    dir: ./0-basic
  pipeline:
    taskfile: ./1-pipeline/Taskfile.yml
    dir: ./1-pipeline
  iopipe:
    taskfile: ./2-iopipe/Taskfile.yml
    dir: ./2-iopipe
  multi-sfn:
    taskfile: ./3-multi-sfn/Taskfile.yml
    dir: ./3-multi-sfn
  cascading-zipper:
    taskfile: ./4-cascading-zipper/Taskfile.yml
    dir: ./4-cascading-zipper

tasks:
  example-basic:
    desc: YoMo basic usage
    silent: false
    cmds:
      - task: basic:run

  example-pipeline:
    desc: Unix pipeline to cloud
    silent: false
    cmds:
      - task: pipeline:run

  example-iopipe:
    desc: IO Pipe
    silent: false
    cmds:
      - task: iopipe:run

  example-multi-sfn:
    desc: Multiple stream functions
    silent: false
    cmds:
      - task: multi-sfn:run

  example-cascading-zipper:
    desc: Cascading zippers
    silent: false
    cmds:
      - task: cascading-zipper:run

  # example cleanup
  clean:
    desc: clean
    silent: true
    cmds:
      - echo 'example cleaning...'
      - task: basic:clean
      - task: pipeline:clean
      - task: iopipe:clean
      - task: multi-sfn:clean
      - task: cascading-zipper:clean
