# https://taskfile.dev

version: "3"

output: "prefixed"

tasks:
  default:
    dir: ./example
    cmds:
      - echo "Go to ./example for detail usage, like [task basic:run]"
      - echo "🍭 all examples list here"
      - ls ./
      - echo "🍭 all tasks list here"
      - task -l
    silent: true
