# https://taskfile.dev

version: "3"

output: "prefixed"

tasks:
  run:
    desc: run
    deps: [zipper, source, sfn-1, sfn-2]
    cmds:
      - echo 'backflow example run'

  # example cleanup
  clean:
    desc: clean
    cmds:
      - rm -rf ./bin

  build:
    desc: build source, sfns and zipper
    deps: [source-build, sfn-1-build, sfn-2-build]
    cmds:
      - echo 'building done'

  source:
    desc: run source
    deps: [source-build]
    cmds:
      - "./bin/source{{exeExt}}"
    env:
      YOMO_LOG_LEVEL: error

  source-build:
    desc: build source
    cmds:
      - "go build -o ./bin/source{{exeExt}} source/main.go"

  sfn-1:
    desc: run sfn-1
    deps: [sfn-1-build]
    cmds:
      - "./bin/sfn-1{{exeExt}}"
    env:
      YOMO_LOG_LEVEL: error

  sfn-1-build:
    desc: build sfn-1
    cmds:
      - "go build -o ./bin/sfn-1{{exeExt}} sfn-1/main.go"

  sfn-2:
    desc: run sfn-2
    deps: [sfn-2-build]
    cmds:
      - "./bin/sfn-2{{exeExt}}"
    env:
      YOMO_LOG_LEVEL: error

  sfn-2-build:
    desc: build sfn-2
    cmds:
      - "go build -o ./bin/sfn-2{{exeExt}} sfn-2/main.go"

  zipper:
    desc: run zipper
    cmds:
      - "yomo serve -c workflow.yaml"
    env:
      YOMO_LOG_LEVEL: error
