# https://taskfile.dev

version: "3"

output: "prefixed"

env:
  YOMO_LOG_LEVEL: error
  # set the following environment values on production mode
  # YOMO_TLS_VERIFY_PEER: true
  # YOMO_TLS_CACERT_FILE: "../../test/tls/ca.crt"
  # YOMO_TLS_CERT_FILE: "../../test/tls/client.crt"
  # YOMO_TLS_KEY_FILE: "../../test/tls/client.key"

tasks:
  run:
    desc: run
    deps: [source, sfn, zipper]

  # example cleanup
  clean:
    desc: cleanup
    cmds:
      - rm -rf ./bin

  zipper:
    desc: run zipper
    cmds:
      - "yomo serve -c ../config.yaml"
    env:
      YOMO_LOG_LEVEL: error
      # set the following environment values on production mode
      # YOMO_TLS_VERIFY_PEER: true
      # YOMO_TLS_CACERT_FILE: "../../test/tls/ca.crt"
      # YOMO_TLS_CERT_FILE: "../../test/tls/server.crt"
      # YOMO_TLS_KEY_FILE: "../../test/tls/server.key"
      #
      YOMO_TRACE_JAEGER_ENDPOINT: "http://localhost:14268/api/traces"

  source-build:
    desc: build source
    cmds:
      - "go build -o ./bin/source{{exeExt}} source/main.go"
    internal: true

  source:
    desc: run source
    deps: [source-build]
    cmds:
      - "go build -o ./bin/source{{exeExt}} source/main.go"
      - "./bin/source{{exeExt}}"
    env:
      YOMO_LOG_LEVEL: debug
      YOMO_TRACE_JAEGER_ENDPOINT: "http://localhost:14268/api/traces"

  sfn:
    desc: run stream functions
    deps: [sfn-1, sfn-2, sfn-3, sfn-4]

  sfn-1:
    desc: run stream functions 1
    cmds:
      - "go build -o ./bin/sfn-1{{exeExt}} ./stream-fn-1/app.go"
      - "./bin/sfn-1{{exeExt}}"
    env:
      YOMO_LOG_LEVEL: debug
      YOMO_TRACE_JAEGER_ENDPOINT: "http://localhost:14268/api/traces"

  sfn-2:
    desc: run stream functions 2
    cmds:
      - "go build -o ./bin/sfn-2{{exeExt}} ./stream-fn-2/app.go"
      - "./bin/sfn-2{{exeExt}}"
    env:
      YOMO_LOG_LEVEL: debug
      YOMO_TRACE_JAEGER_ENDPOINT: "http://localhost:14268/api/traces"

  sfn-3:
    desc: run stream functions 3
    cmds:
      - "go build -o ./bin/sfn-3{{exeExt}} ./stream-fn-3/app.go"
      - "./bin/sfn-3{{exeExt}}"
    env:
      YOMO_LOG_LEVEL: debug
      YOMO_TRACE_JAEGER_ENDPOINT: "http://localhost:14268/api/traces"

  sfn-4:
    desc: run stream functions 4
    cmds:
      - "go build -o ./bin/sfn-4{{exeExt}} ./stream-fn-4/app.go"
      - "./bin/sfn-4{{exeExt}}"
    env:
      YOMO_LOG_LEVEL: debug
      YOMO_TRACE_JAEGER_ENDPOINT: "http://localhost:14268/api/traces"
