# https://taskfile.dev

version: "3"

output: "prefixed"

tasks:
  run:
    desc: run
    deps: [clean]
    cmds:
      - echo '9-cli example run'
      - task: sfn-build
      - task: start

  # example cleanup
  clean:
    desc: clean
    cmds:
      - rm -rf ./bin
      - rm -rf ./sfn/*.wasm

  start:
    desc: Start
    deps: [zipper, sfn, source]
    cmds:
      - echo 'start done'

  source-build:
    desc: build source
    dir: source
    cmds:
      - "go build -o ../bin/source{{exeExt}} main.go"

  sfn-build:
    desc: build sfn
    dir: sfn
    cmds:
      - "yomo build -m go.mod app.go"
    status:
      - test -f sfn/sfn.wasm

  source:
    desc: run source
    deps: [source-build]
    env:
      YOMO_LOG_LEVEL: error
    cmds:
      - "./bin/source{{exeExt}}"

  sfn:
    desc: run sfn
    dir: sfn
    cmds:
      - "yomo run sfn.wasm"
    env:
      YOMO_LOG_LEVEL: error
    preconditions:
      - test -f sfn.wasm

  zipper:
    desc: run zipper
    cmds:
      - "yomo serve -c config.yaml"
    env:
      YOMO_LOG_LEVEL: error
