# https://taskfile.dev

version: "3"

output: prefixed

env:
  YOMO_LOG_LEVEL: error

tasks:
  default:
    cmds:
      - task -l
    silent: true

  run:
    desc: CLI example
    deps: [zipper, source, sfn-rx, sfn-db]
    cmds:
      - echo "CLI example"

  zipper:
    desc: "run zipper"
    cmds:
      - "yomo serve -c ./zipper/workflow.yaml"
    silent: false
    env:
      YOMO_AUTH: token:1234

  source:
    desc: run source application
    deps: [source-build]
    cmds:
      - "./bin/source{{exeExt}}"
    silent: false
    env:
      YOMO_CREDENTIAL: token:1234

  source-build:
    desc: build source application
    cmds:
      - echo "source building..."
      - "go build -o ./bin/source{{exeExt}} ./source/main.go"
      - echo "source built."
    silent: false

  sfn-rx:
    desc: "run rx stream application"
    dir: "sfn-rx"
    cmds:
      - "yomo run app.go"
    silent: false

  sfn-db:
    desc: run output stream-fn-db
    dir: "sfn-db"
    cmds:
      - "yomo run app.go"
    silent: false

  clean:
    desc: "cli clean"
    cmds:
      - rm -rf ./bin
    silent: true
