# https://taskfile.dev

version: "3"

output: "prefixed"

env:
  YOMO_LOG_LEVEL: error

tasks:
  run:
    desc: run
    deps: [sfn, source, zipper-1, zipper-2]


  zipper-1:
    desc: run zipper-1
    cmds:
      - "yomo serve -c zipper_1.yaml"

  zipper-2:
    desc: run zipper-2
    cmds:
     - "yomo serve -c zipper_2.yaml"

  sfn:
    desc: sfn
    deps: [sfn-build]
    cmds:
      - "./bin/sfn{{exeExt}}"

  source:
    desc: source
    deps: [source-build]
    cmds:
      - "./bin/source{{exeExt}}"

  clean:
    desc: clean
    cmds:
      - "rm -rf ./bin"

  source-build:
    desc: build source
    cmds:
      - "go build -o ./bin/source{{exeExt}} source/source.go"
    internal: true

  sfn-build:
    desc: build sfn
    cmds:
      - "go build -o ./bin/sfn{{exeExt}} sfn/sfn_echo.go"
    internal: true
