# https://taskfile.dev

version: "3"

output: "prefixed"

tasks:
  run:
    desc: run
    cmds:
      - task: sfn-build
      - task: start

  start:
    desc: start
    deps: [zipper, sfn, source]


  sfn-build:
    desc: sfn-build
    dir: serverless
    cmds:
      - "yomo build serverless/rand.go"

  zipper:
    desc: zipper
    cmds:
      - "yomo serve -c config.yaml"
    env:
      YOMO_LOG_LEVEL: error

  sfn:
    desc: sfn
    dir: serverless
    cmds:
      - "yomo run sfn.wasm -n rand -m go.mod"

  source:
    desc: source
    cmds:
      - "cat /dev/urandom | go run source/pipe.go"

  clean:
    desc: clean
    cmds:
      - "rm -rf ./serverless/sfn.*"
