# https://taskfile.dev

version: "3"

output: "prefixed"

tasks:
  run:
    desc: run
    deps: [zipper, sfn, source]

  zipper:
    desc: zipper
    cmds:
      - "yomo serve -c config.yaml"
    env:
      YOMO_LOG_LEVEL: error

  sfn:
    desc: sfn
    cmds:
      - "yomo build serverless/rand.go && yomo run serverless/sfn.wasm -n rand"

  source:
    desc: source
    cmds:
      - "cat /dev/urandom | go run source/pipe.go"

  clean:
    desc: clean
    cmds:
      - "rm -rf ./serverless/sfn.*"
