# https://taskfile.dev

version: "3"

output: "prefixed"

tasks:
  run:
    desc: run
    cmds:
      - task: sfn-build
      - task: start

  start:
    desc: start
    deps: [zipper, sfn, source]

  zipper:
    desc: zipper
    cmds:
      - "yomo serve -c config.yaml"
    env:
      YOMO_LOG_LEVEL: error

  sfn-build:
    desc: sfn build
    cmds:
      # - "yomo build serverless/rand.go" # use latest yomo
      - "yomo build -m go.mod serverless/rand.go" # use custom go.mod for development

  sfn:
    desc: run sfn
    cmds:
      - "yomo run -m go.mod -n rand serverless/sfn.wasm"

  source:
    desc: source
    cmds:
      - "cat /dev/urandom | go run source/pipe.go"

  clean:
    desc: clean
    cmds:
      - "rm -rf ./serverless/sfn.*"
