# https://taskfile.dev

version: '3'

output: "prefixed"

tasks:
  run:
    desc: run
    deps: [zipper, source, sfn]
    cmds:
      - echo 'wasm example run'
    silent: true

  clean:
    desc: clean
    cmds:
      - rm -rf ./bin

  source:
    desc: run source
    deps: [source-build]
    cmds:
      - "./bin/source{{exeExt}}"
    env:
      YOMO_LOG_LEVEL: error

  source-build:
    desc: build source
    cmds:
      - "go build -o ./bin/source{{exeExt}} source/main.go"

  sfn:
    desc: run sfn
    dir: sfn
    cmds:
      - "yomo run sfn.wasm"

  zipper:
    desc: run zipper
    cmds:
      - "yomo serve -c workflow.yaml"
    env:
      YOMO_LOG_LEVEL: error
      YOMO_ADDR: "localhost:9000"
