# https://taskfile.dev

version: "3"

output: "prefixed"

tasks:
  run:
    desc: run
    deps: [zipper, source, sfn]
    cmds:
      - echo 'deno example run'
    silent: true

  clean:
    desc: clean
    cmds:
      - rm -rf ./bin

  source:
    desc: run source
    deps: [source-build]
    cmds:
      - "../uppercase/bin/source{{exeExt}}"
    env:
      YOMO_LOG_LEVEL: error

  source-build:
    desc: build source
    cmds:
      - "go build -o ../uppercase/bin/source{{exeExt}} ../uppercase/source/main.go"
    internal: true

  sfn:
    desc: run sfn
    cmds:
      - "yomo run app.ts"

  zipper:
    desc: run zipper
    cmds:
      - "yomo serve -c ../uppercase/config.yaml"
    env:
      YOMO_LOG_LEVEL: error
      YOMO_ADDR: "localhost:9000"
