# https://taskfile.dev

version: '3'

output: "prefixed"

vars:
  ExeName: yomo{{exeExt}}

tasks:
  run:
    desc: run
    deps: [zipper, source, sfn]
    cmds:
      - echo 'deno example run'
    silent: true

  clean:
    desc: clean
    cmds:
      - rm -rf ./bin

  build:
    desc: build yomo cli tools
    cmds:
      - go build -v -o ./bin/{{.ExeName}} -ldflags "-s -w -X {{.Module}}/cli.Version={{.Version}} -X {{.Module}}/cli.Date={{.Date}}" ../../cmd/yomo/main.go
    method: none
    silent: true

  source:
    desc: run source
    deps: [source-build]
    cmds:
      - "./bin/source{{exeExt}}"
    env:
      YOMO_LOG_LEVEL: error

  source-build:
    desc: build source
    cmds:
      - "go build -o ./bin/source{{exeExt}} source/main.go"

  sfn:
    desc: run sfn
    deps: [build]
    cmds:
      - "./bin/yomo{{exeExt}} run app.ts"

  zipper:
    desc: run zipper
    deps: [build]
    cmds:
      - "./bin/yomo{{exeExt}} serve -c workflow.yaml"
    env:
      YOMO_LOG_LEVEL: error
      YOMO_ADDR: "localhost:9000"
