# https://taskfile.dev

version: "3"

output: "prefixed"

env:
  YOMO_LOG_LEVEL: error

vars:
  ExeName: yomo{{exeExt}}

tasks:
  run:
    desc: run
    deps: [us, eu]
    cmds:
      - echo 'mesh example run'
    silent: true

  clean:
    desc: clean
    cmds:
      - rm -rf ./bin
      - rm -rf ./stream-fn/bin
      - rm -rf ./stream-fn-db/bin

  build:
    desc: build yomo cli tools
    cmds:
      - go build -v -o ./bin/{{.ExeName}} -ldflags "-s -w -X {{.Module}}/cli.Version={{.Version}} -X {{.Module}}/cli.Date={{.Date}}" ../../cmd/yomo/main.go
    method: none
    silent: true

  us:
    desc: mesh-us
    deps:
      [
        zipper-sender-us,
        zipper-receiver-us,
        stream-fn-us,
        stream-fn-db-us,
        source-us,
      ]
    cmds:
      - echo "mesh-us"

  eu:
    desc: mesh-eu
    deps:
      [
        zipper-sender-eu,
        zipper-receiver-eu,
        stream-fn-eu,
        stream-fn-db-eu,
        source-eu,
      ]
    cmds:
      - echo "mesh-eu"

  zipper-sender-us:
    desc: "run zipper-sender-us"
    deps: [build]
    cmds:
      - "./bin/{{.ExeName}} serve -c us/sender.yaml"
    silent: false

  zipper-receiver-us:
    desc: "run zipper-receiver-us"
    deps: [build]
    cmds:
      - "./bin/{{.ExeName}} serve -c us/receiver.yaml"
    silent: false

  zipper-sender-eu:
    desc: "run zipper-sender-eu"
    deps: [build]
    cmds:
      - "./bin/{{.ExeName}} serve -c eu/sender.yaml"
    silent: false

  zipper-receiver-eu:
    desc: "run zipper-receiver-eu"
    deps: [build]
    cmds:
      - "./bin/{{.ExeName}} serve -c eu/receiver.yaml"
    silent: false

  source-us:
    desc: run source application
    deps: [source-build]
    cmds:
      - "cp ./bin/source{{exeExt}} ./bin/source-us{{exeExt}}"
      - "./bin/source-us{{exeExt}}"
    env:
      PORT: 9000
      REGION: "💖 US 💖"
    silent: false

  source-eu:
    desc: run source application
    deps: [source-build]
    cmds:
      - "cp ./bin/source{{exeExt}} ./bin/source-eu{{exeExt}}"
      - "./bin/source-eu{{exeExt}}"
    env:
      PORT: 9800
      REGION: "💙 EU 💙"
    silent: false

  source-build:
    desc: build source application
    cmds:
      - echo "source building..."
      - "go build -o ./bin/source{{exeExt}} ./source/main.go"
      - echo "source built."
    silent: false
    internal: true

  stream-fn-us:
    desc: run stream function
    deps: [stream-fn-build]
    dir: "stream-fn"
    cmds:
      - "cp ./bin/stream-fn{{exeExt}} ./bin/stream-fn-us{{exeExt}}"
      - "./bin/stream-fn-us{{exeExt}}"
    env:
      PORT: 9000
      REGION: "💖 US 💖"
    silent: false

  stream-fn-eu:
    desc: run stream function
    deps: [stream-fn-build]
    dir: "stream-fn"
    cmds:
      - "cp ./bin/stream-fn{{exeExt}} ./bin/stream-fn-eu{{exeExt}}"
      - "./bin/stream-fn-eu{{exeExt}}"
    env:
      PORT: 9800
      REGION: "💙 EU 💙"
    silent: false

  stream-fn-build:
    desc: build stream function
    dir: "stream-fn"
    cmds:
      - "go build -o ./bin/stream-fn{{exeExt}} app.go"
    silent: false
    internal: true

  stream-fn-db-us:
    desc: run output stream-fn-db
    deps: [stream-fn-db-build]
    dir: "stream-fn-db"
    cmds:
      - "cp ./bin/stream-fn-db{{exeExt}} ./bin/stream-fn-db-us{{exeExt}}"
      - "./bin/stream-fn-db-us{{exeExt}}"
    env:
      PORT: 9001
    silent: false

  stream-fn-db-eu:
    desc: run output stream-fn-db
    deps: [stream-fn-db-build]
    dir: "stream-fn-db"
    cmds:
      - "cp ./bin/stream-fn-db{{exeExt}} ./bin/stream-fn-db-eu{{exeExt}}"
      - "./bin/stream-fn-db-eu{{exeExt}}"
    env:
      PORT: 9801
    silent: false

  stream-fn-db-build:
    desc: build output stream-fn-db
    dir: "stream-fn-db"
    cmds:
      - "go build -o ./bin/stream-fn-db{{exeExt}} app.go"
    silent: false
    internal: true
