# https://taskfile.dev

version: "3"

output: "prefixed"

tasks:
  run:
    desc: run
    cmds: 
      - task: sfn-build
      - task: start

  start:
    desc: start
    deps: [zipper, sfn, source]

  zipper:
    desc: zipper
    cmds:
      - "yomo serve -c config.yaml"
    env:
      YOMO_LOG_LEVEL: error

  sfn-build:
    desc: sfn build
    cmds:
      - task: clean
      - "yomo build serverless/counter.go"

  sfn:
    desc: sfn
    cmds:
      # - "yomo run -n counter serverless/counter.go" # use latest yomo
      - "yomo run serverless/sfn.wasm -n counter" # use custom go.mod for development

  source:
    desc: source
    cmds:
      - "cat /dev/urandom | go run source/pipe.go"

  clean:
    desc: clean
    cmds:
      - "rm -rf ./serverless/sfn.wasm"
