# https://taskfile.dev

version: "3"

output: "prefixed"

tasks:
  run:
    desc: run
    deps: [zipper, source, sfn1, sfn2]
    cmds:
      - echo 'basic example run'

  # example cleanup
  clean:
    desc: clean
    cmds:
      - rm -rf ./bin

  build:
    desc: build source, sfns and zipper
    deps: [source-build, sfn1-build, sfn2-build]
    cmds:
      - echo 'building done'

  source-build:
    desc: build source
    cmds:
      - "go build -o ./bin/source{{exeExt}} source/main.go"

  sfn1-build:
    desc: build sfn1
    cmds:
      - "go build -o ./bin/sfn1{{exeExt}} sfn/main.go"

  source:
    desc: run source
    deps: [source-build]
    cmds:
      - "./bin/source{{exeExt}}"
    env:
      YOMO_LOG_LEVEL: error

  sfn1:
    desc: run sfn1
    deps: [sfn1-build]
    cmds:
      - "./bin/sfn1{{exeExt}}"
    env:
      YOMO_LOG_LEVEL: error

  sfn2-build:
    desc: build sfn2
    cmds:
      - "go build -o ./bin/sfn2{{exeExt}} sfn2/main.go"

  sfn2:
    desc: run sfn2
    deps: [sfn2-build]
    cmds:
      - "./bin/sfn2{{exeExt}}"
    env:
      YOMO_LOG_LEVEL: error

  zipper:
    desc: run zipper
    cmds:
      - "yomo serve -c workflow.yaml"
    env:
      YOMO_LOG_LEVEL: error
      YOMO_ADDR: "localhost:9000"
      YOMO_LOG_ERROR_OUTPUT: err.log
